### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by yasharels**

### CODE REVIEW

**Comment by Zayelion** [comment]
Are you taking on building out this thing or.... ?

**Comment by yasharels** [comment]
What do you mean?

**Comment by yasharels** [comment]
Was this abandoned...?

**Comment by Zayelion** [comment]
BLS's intent is for the UI of DN to be reworked into a websocket - html system, and not a flash based one. If you can get it working he'll consider it for implementation. The administration at DN is very against change, I believe they saw the project as a threat. The staff here at Salvation had trouble working with them and we had our own issues to solve so we became a YGOPro variant instead of helping.

You'll need something that proxies TCP to websocket, I can explain what you need to do and review code for you.

**Comment by yasharels** [comment]
I don't think i'll consider helping with that, sorry. I've never used YGOpro and have barely seen it.

**Comment by Zayelion** [comment]
Well if you are going to work on DNjs, just keep putting in patches.

**Comment by yasharels** [comment]
Sure.

**Pull request merged**
